name: PEP8 Validation

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Validator Repo
        uses: actions/checkout@v4

      - name: Clone Target Repo 1
        run: |
          git clone https://github.com/VrajeshActalent/UTC_Helper.git

      - name: Clone Target Repo 2
        run: |
          git clone https://github.com/VrajeshActalent/SpellChecker.git

      - name: Install Dependencies
        run: |
          pip install pylint pandas openpyxl

      - name: Get Changed Files from Target Repos
        run: |
          > changed_files.txt

          cd UTC_Helper
          git diff --name-only HEAD~1 HEAD >> ../changed_files.txt || git ls-files >> ../changed_files.txt
          cd ..

          cd SpellChecker
          git diff --name-only HEAD~1 HEAD >> ../changed_files.txt || git ls-files >> ../changed_files.txt
          cd ..
          
      - name: Run Validation
        run: |
          python generate_report.py

      - name: Read Report Name
        run: |
          echo "REPORT_FILE=$(cat report_name.txt)" >> $GITHUB_ENV

      - name: Upload Excel Reports
        uses: actions/upload-artifact@v4
        with:
          name: Pylint_Reports
          path: "*.xlsx"
